KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  user_admin="admin123"
  user_kafka="admin123"
  user_readonly_admin="admin123";
};

Client {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  username="kafka"
  password="admin123";
};

KafkaClient {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="admin123";
};
