KafkaServer {
  org.apache.kafka.common.security.plain.PlainLoginModule required
  username="admin"
  password="kafka_secure_pass_2025"
  user_admin="kafka_secure_pass_2025"
  user_kafka="kafka_secure_pass_2025"
  user_readonly_admin="readonly_kafka_2025";
};

Client {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  username="kafka"
  password="kafka_secure_pass_2025";
};
