Server {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  user_kafka="admin123"
  user_admin="admin123"
  user_readonly_admin="admin123";
};

QuorumServer {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  user_kafka="admin123";
};

