Server {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  user_kafka="kafka_secure_pass_2025"
  user_admin="kafka_secure_pass_2025"
  user_readonly_admin="readonly_kafka_2025";
};

QuorumServer {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  user_kafka="kafka_secure_pass_2025";
};

