
Server {
   org.apache.zookeeper.server.auth.DigestLoginModule required
   user_kafka="kafka_secure_pass_2026"
   user_admin="kafka_secure_pass_2026"
   user_readonly_admin="readonly_kafka_2026";
   };

QuorumServer {
  org.apache.zookeeper.server.auth.DigestLoginModule required
  user_kafka="kafka_secure_pass_2025";
};

