import os
from sqlalchemy import create_engine, Column, Integer, String, Numeric, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import datetime

DATABASE_URL = os.getenv("DATABASE_URL")

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

class Transaction(Base):
    __tablename__ = "transactions"
    id = Column(String, primary_key=True) # UUID generated by API
    account_id = Column(Integer, index=True)
    amount = Column(Numeric(15, 2))
    category = Column(String)
    merchant = Column(String)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)