import os
from sqlalchemy import create_engine, Column, Integer, String, Numeric, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
import datetime

# Database Configuration
POSTGRES_USER = os.getenv("POSTGRES_USER", "admin")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "")
POSTGRES_DB = os.getenv("POSTGRES_DB", "banking_db")
POSTGRES_HOST = os.getenv("POSTGRES_HOST", "localhost")
POSTGRES_PORT = os.getenv("POSTGRES_PORT", "5432")

DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"

engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    first_name = Column(String(50), nullable=False)
    last_name = Column(String(50), nullable=False)
    email = Column(String(100), unique=True, index=True, nullable=False)
    password_hash = Column(String(255), nullable=False)
    # Use server_default to ensure existing rows get a value during migration
    role = Column(String(20), default="user", server_default="user", nullable=False)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

class Account(Base):
    __tablename__ = "accounts"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    balance = Column(Numeric(15, 2), default=0.00)

class Transaction(Base):
    __tablename__ = "transactions"
    id = Column(String, primary_key=True) # UUID generated by API
    parent_id = Column(String, index=True, nullable=True) # Links Debit/Credit pairs
    account_id = Column(Integer, ForeignKey("accounts.id"), index=True)
    amount = Column(Numeric(15, 2))
    category = Column(String)
    merchant = Column(String)
    status = Column(String, default="pending") # pending, sent_to_kafka, cleared
    transaction_type = Column(String, default="expense") # expense, income, transfer
    transaction_side = Column(String(10)) # DEBIT or CREDIT
    idempotency_key = Column(String(100), index=True)
    ip_address = Column(String(45))
    user_agent = Column(String(255))
    failure_reason = Column(String(255))
    created_at = Column(DateTime, default=datetime.datetime.utcnow)


from sqlalchemy.dialects.postgresql import JSONB

class IdempotencyKey(Base):
    __tablename__ = "idempotency_keys"
    id = Column(Integer, primary_key=True)
    key = Column(String(100), unique=True, index=True, nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False)
    response_code = Column(Integer)
    response_body = Column(JSONB)
    created_at = Column(DateTime, default=datetime.datetime.utcnow)

class Outbox(Base):
    __tablename__ = "outbox"
    id = Column(Integer, primary_key=True)
    event_type = Column(String(50), nullable=False)
    payload = Column(JSONB, nullable=False)

    status = Column(String(20), default="pending")
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    processed_at = Column(DateTime, nullable=True)
