"""refactor_money_to_cents_and_add_account_uuid

Revision ID: 9c37a5071631
Revises: aa6c5010c512
Create Date: 2026-03-14 19:38:36.950559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c37a5071631'
down_revision: Union[str, Sequence[str], None] = 'aa6c5010c512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_uuid', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_accounts_account_uuid'), 'accounts', ['account_uuid'], unique=True)

    # 1. Convert money values to cents (Numeric * 100) before changing type
    # Postgres handles the Numeric -> BigInt conversion via USING clause in ALTER TABLE
    op.execute("ALTER TABLE accounts ALTER COLUMN balance TYPE BIGINT USING (balance * 100)::BIGINT")
    op.execute("ALTER TABLE accounts ALTER COLUMN reserved_balance TYPE BIGINT USING (reserved_balance * 100)::BIGINT")
    op.execute("ALTER TABLE payment_requests ALTER COLUMN amount TYPE BIGINT USING (amount * 100)::BIGINT")
    op.execute("ALTER TABLE scheduled_payments ALTER COLUMN amount TYPE BIGINT USING (amount * 100)::BIGINT")
    op.execute("ALTER TABLE subscriptions ALTER COLUMN amount TYPE BIGINT USING (amount * 100)::BIGINT")
    op.execute("ALTER TABLE transactions ALTER COLUMN amount TYPE BIGINT USING (amount * 100)::BIGINT")

    # 2. Populate account_uuid for existing rows
    import uuid
    # Note: For large databases, this should be done in batches. For a bank-dev-db, this is fine.
    # We'll use a postgres-compatible way to generate UUIDs if possible, or just a simple loop in python.
    # Actually, a simple SQL update is better:
    op.execute("UPDATE accounts SET account_uuid = gen_random_uuid()::text WHERE account_uuid IS NULL")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE transactions ALTER COLUMN amount TYPE NUMERIC(15, 2) USING (amount::NUMERIC / 100)")
    op.execute("ALTER TABLE subscriptions ALTER COLUMN amount TYPE NUMERIC(15, 2) USING (amount::NUMERIC / 100)")
    op.execute("ALTER TABLE scheduled_payments ALTER COLUMN amount TYPE NUMERIC(15, 2) USING (amount::NUMERIC / 100)")
    op.execute("ALTER TABLE payment_requests ALTER COLUMN amount TYPE NUMERIC(15, 2) USING (amount::NUMERIC / 100)")
    op.execute("ALTER TABLE accounts ALTER COLUMN balance TYPE NUMERIC(15, 2) USING (balance::NUMERIC / 100)")
    op.execute("ALTER TABLE accounts ALTER COLUMN reserved_balance TYPE NUMERIC(15, 2) USING (reserved_balance::NUMERIC / 100)")

    op.drop_index(op.f('ix_accounts_account_uuid'), table_name='accounts')
    op.drop_column('accounts', 'account_uuid')
    # ### end Alembic commands ###
